#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci_sequence = [1,2]
even_fib_seq = []
answer = 0
max = 4000000

def extend_fib_seq(upper_limit):
    while fibonacci_sequence[-1] + fibonacci_sequence[-2] < upper_limit:
        next_term = fibonacci_sequence[-1] + fibonacci_sequence[-2]
        fibonacci_sequence.append(next_term)

extend_fib_seq(max)

for k in fibonacci_sequence:
    if k % 2 == 0:
        even_fib_seq.append(k)

for j in even_fib_seq:
    answer = answer + j

print(answer)